// <auto-generated/>
using System.Reflection;
using System.Runtime.InteropServices;

[assembly: AssemblyTitleAttribute("Societly UI")]
[assembly: AssemblyDescriptionAttribute("A game with a sweet tagline")]
[assembly: AssemblyProductAttribute("Societly UI")]
[assembly: AssemblyVersionAttribute("0.1.0")]
[assembly: AssemblyFileVersionAttribute("0.1.0")]
[assembly: ComVisibleAttribute(false)]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const string Version = "0.1.0";
    }
}
